# Generated by Django 6.0.1 on 2026-01-14 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_contact', models.CharField(max_length=20)),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person')], max_length=20)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'), models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_fb412a_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_appointment_slot')],
            },
        ),
    ]
