# Generated by Django 6.0.1 on 2026-01-14 15:52

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(db_index=True, max_length=100)),
                ('bio', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('consultation_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctors_doctor',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialization', 'is_active'], name='doctors_doc_special_78e3fa_idx')],
            },
        ),
    ]
