# Generated by Django 6.0.1 on 2026-01-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_modes',
        ),
        migrations.AddField(
            model_name='doctor',
            name='_consultation_modes',
            field=models.JSONField(default=list),
        ),
    ]
